### ISSUE TITLE
[Q] Where to find a data dump for data on the website

### ISSUE THREAD

**Issue by nodiscc** [lfzawacki/musical-artifacts#7]
Hi, hope you don't mind the few items I have added to the issues tracker. I mostly added them as a personal reminder, if you want I can work on adding them to the database myself. FYI I have removed those items from https://github.com/nodiscc/awesome-linuxaudio and linked directly to your site which does a much better job. So congrats again.

My main question: I would like to backup the site for offline use/archival/reference/mirroring including the data about artifacts. Maybe work on an automated linux audio workstation setup script. Where can I download the data as a dump without crawling the site? Is the db format compatible with git hosting/collaboration? I wish it was possible to contribute to the artifacts db using git/Github.

Thanks again

**Comment by lfzawacki** [comment]
Hi, about the issues, no problem . It would be nice if you could add the files to the site or leave them as open issues here to wait and see if other people would be interested.

About the data dump, I've been thinking about it and actually already have a system which copies the database and files to another server for backup purposes. I could as well just serve these files for download, have instructions on how to run a mirror of the site with this data and maybe a JSON or XML dump of all the artifacts together with it.

I'll leave this issue open to ideas and suggestions on what people would want from this data and I'll keep you posted on the updates on the implementation side.

About adding artifacts via git, there's nothing of the sort right now ... but if you want to get creative there's the json API https://github.com/lfzawacki/musical-artifacts/wiki/API-Documentation

**Comment by nodiscc** [comment]
If you are able to export the db as JSON, you could push it to a repo on github and let people edit it there (problem is handling merge conflicts when it has been edited both on gh and on the site). We did this at https://github.com/RequestPolicyContinued/subscriptions. The API also looks nice.

I will take care of the bug reports when I get some time. Thanks for the quick reply

**Comment by lfzawacki** [comment]
Thought you might want to know that I have the data backups currently at https://data.musical-artifacts.com/ It's the database with artifacts and comments, but without the user table and other irrelevant data. The backups will be done weekly and soon I'll have a guide up on how to run your own mirror of the site with this data, as well as a json dump.

About the json + git idea, I was thinking about making some extra verbose options for the '/artifacts.json' index output and then have this json file containing all the artifacts be stored together with the database and files. Having this we could orchestrate a system where some people contribute via a git repository with json files and these are later synced with the database. I won't promise to work on this very soon because my focus isn't tech savvy users, e.g., those who would rather use git.

This issue remains open in the meantime.

**Comment by lfzawacki** [comment]
Now data.musical-artifacts.com now has json files for all the data in the website. These files are created as part of the data backup process and are just a linted and formatted json output of all the data which can be queried via the API. This data can be used for the git repository approach if you want to.

**Comment by nodiscc** [comment]
Thanks, I have imported json files to https://github.com/nodiscc/musical-artifacts-data, I'll experiment with it.

What remains to be done in my opinion:

 - [ ] add link to https://data.musical-artifacts.com/ in this repo's README
 - [ ] add link to https://data.musical-artifacts.com/ on https://musical-artifacts.com/info/about

Then this issue can be closed. Thanks again for your work @lfzawacki

**Comment by lfzawacki** [comment]
The data and your repository are linked on the README and the main wiki page. Closing the issue now.
